// Mocks generated by Mockito 5.4.6 from annotations
// in biblia/test/presentation/viewmodels/chapter_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:biblia/domain/repositories/database_repository.dart' as _i2;
import 'package:biblia/domain/usecases/get_chapters_usecase.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseRepository_0 extends _i1.SmartFake
    implements _i2.DatabaseRepository {
  _FakeDatabaseRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetChaptersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChaptersUseCase extends _i1.Mock
    implements _i3.GetChaptersUseCase {
  MockGetChaptersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDatabaseRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DatabaseRepository);

  @override
  _i4.Future<int> call({required int? bookId}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#bookId: bookId},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
