// Mocks generated by Mockito 5.4.6 from annotations
// in biblia/test/presentation/viewmodels/verse_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:biblia/domain/entities/verse.dart' as _i5;
import 'package:biblia/domain/repositories/database_repository.dart' as _i2;
import 'package:biblia/domain/usecases/get_verses_usecase.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseRepository_0 extends _i1.SmartFake
    implements _i2.DatabaseRepository {
  _FakeDatabaseRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetVersesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVersesUseCase extends _i1.Mock implements _i3.GetVersesUseCase {
  MockGetVersesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDatabaseRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DatabaseRepository);

  @override
  _i4.Future<List<_i5.Verse>> call({
    int? bookId,
    int? chapterId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #bookId: bookId,
            #chapterId: chapterId,
          },
        ),
        returnValue: _i4.Future<List<_i5.Verse>>.value(<_i5.Verse>[]),
      ) as _i4.Future<List<_i5.Verse>>);
}
