// Mocks generated by Mockito 5.4.6 from annotations
// in biblia/test/data/repositories/fallback_database_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:biblia/core/utils/config_service.dart' as _i8;
import 'package:biblia/data/datasources/remote/biblia_remote_data_source.dart'
    as _i2;
import 'package:biblia/domain/entities/book.dart' as _i5;
import 'package:biblia/domain/entities/testament.dart' as _i6;
import 'package:biblia/domain/entities/verse.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BibliaRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBibliaRemoteDataSource extends _i1.Mock
    implements _i2.BibliaRemoteDataSource {
  MockBibliaRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i4.Future<List<_i5.Book>> getBooks({int? testamentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
          {#testamentId: testamentId},
        ),
        returnValue: _i4.Future<List<_i5.Book>>.value(<_i5.Book>[]),
      ) as _i4.Future<List<_i5.Book>>);

  @override
  _i4.Future<List<_i6.Testament>> getTestaments() => (super.noSuchMethod(
        Invocation.method(
          #getTestaments,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Testament>>.value(<_i6.Testament>[]),
      ) as _i4.Future<List<_i6.Testament>>);

  @override
  _i4.Future<int> getChapters(int? bookId) => (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [bookId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.Verse>> getVerses({
    int? bookId,
    int? chapterId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerses,
          [],
          {
            #bookId: bookId,
            #chapterId: chapterId,
          },
        ),
        returnValue: _i4.Future<List<_i7.Verse>>.value(<_i7.Verse>[]),
      ) as _i4.Future<List<_i7.Verse>>);

  @override
  _i4.Future<List<_i7.Verse>> getVersesByRange({
    required int? bookId,
    required int? chapter,
    int? startVerse,
    int? endVerse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVersesByRange,
          [],
          {
            #bookId: bookId,
            #chapter: chapter,
            #startVerse: startVerse,
            #endVerse: endVerse,
          },
        ),
        returnValue: _i4.Future<List<_i7.Verse>>.value(<_i7.Verse>[]),
      ) as _i4.Future<List<_i7.Verse>>);

  @override
  _i4.Future<_i5.Book?> findBook(String? name) => (super.noSuchMethod(
        Invocation.method(
          #findBook,
          [name],
        ),
        returnValue: _i4.Future<_i5.Book?>.value(),
      ) as _i4.Future<_i5.Book?>);

  @override
  _i4.Future<List<_i7.Verse>> searchVerses(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVerses,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.Verse>>.value(<_i7.Verse>[]),
      ) as _i4.Future<List<_i7.Verse>>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i8.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isApiEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isApiEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setApiEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setApiEnabled,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
