// Mocks generated by Mockito 5.4.6 from annotations
// in biblia/test/domain/usecases/get_testaments_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:biblia/domain/entities/book.dart' as _i4;
import 'package:biblia/domain/entities/testament.dart' as _i6;
import 'package:biblia/domain/entities/verse.dart' as _i5;
import 'package:biblia/domain/repositories/database_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i2.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> getBooks({int? testament}) => (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
          {#testament: testament},
        ),
        returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
      ) as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<int> getChapters({required int? bookId}) => (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [],
          {#bookId: bookId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.Verse>> getVerses({
    int? bookId,
    int? chapterId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerses,
          [],
          {
            #bookId: bookId,
            #chapterId: chapterId,
          },
        ),
        returnValue: _i3.Future<List<_i5.Verse>>.value(<_i5.Verse>[]),
      ) as _i3.Future<List<_i5.Verse>>);

  @override
  _i3.Future<List<_i6.Testament>> getTestaments() => (super.noSuchMethod(
        Invocation.method(
          #getTestaments,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Testament>>.value(<_i6.Testament>[]),
      ) as _i3.Future<List<_i6.Testament>>);
}
